In [15]:
targetColName="like"
targetIndex=3
lr=[0.05,0.03,0.07,0.01]
origin="drive/MyDrive/twitter/onechunk/"

#Prepare for training

In [16]:
import numpy as np
from xgboost import XGBClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, KFold
import xgboost as xgb

In [17]:
from sklearn.metrics import mean_squared_error

import gc
gc.collect()

88

In [18]:

import os   
os.system(f"cp {origin}* ../content/")

0

In [19]:
import pandas as pd

In [20]:
train=pd.read_csv("trainFinal.csv", index_col=0)
test=pd.read_csv("testFinal.csv", index_col=0)

/usr/local/lib/python3.7/dist-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [21]:
test.columns==train.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [22]:
columns=["retweet","retweetCom","reply","like"]

trainTarget= train[targetColName]
testTarget= test[targetColName]

for col in columns:
    train.drop(col,axis=1,inplace=True)
    test.drop(col,axis=1,inplace=True)
    

##Get data in correct format

In [23]:
trainXGB=train.values
trainTargetXGB=trainTarget.values
del train
del trainTarget

In [24]:
testXGB=test.values
testTargetXGB=testTarget.values
del test
del testTarget

#Model Building

##XGB computation

In [25]:
xgb_params = { 
    'max_depth':8, 
    'learning_rate':0.025, 
    'subsample':0.85,
    'colsample_bytree':0.35, 
    'eval_metric':'logloss',
    'objective':'binary:logistic',
    'seed': 1,
}

In [26]:
xgb_params["learning_rate"]=lr[targetIndex]

In [47]:
xgbc = xgb.XGBClassifier(learning_rate=0.05,max_depth=8,colsample_bytree=0.5,seed=1,base_score=0.9)

In [48]:
trained=xgbc.fit(trainXGB, trainTargetXGB,eval_metric="logloss",verbose=True)

In [49]:
trainPred=trained.predict(trainXGB)

In [50]:
cm = confusion_matrix(trainTargetXGB,trainPred)
cm

array([[1183089,  277189],
       [   9267,  957122]])

In [51]:
testPred=trained.predict(testXGB)

In [52]:
cm = confusion_matrix(testTargetXGB,testPred)
cm

array([[347480,  18556],
       [212308,  28891]])